controller_list:
  - name: fake_arm_group_controller
    joints:
      - rot_joint
      - uarm_joint
      - larm_joint
      - flange_joint
  - name: fake_hand_group_controller
    joints:
      - finger1_joint